### ISSUE TITLE
TALK: What about backward, stepwise and other approaches?

### ISSUE THREAD

**Issue by tobwen** [HannaMeyer/CAST#7]
I know that might me not the best place to start a talk, but this was, others might be able to take place.

As a scientist, I'm torn. An automatic selection of variables are driven by statistical and not theoretical considerations. Of course, the whole thing depends on the research question and the research approach. Fortunately, that's a new field to be explored :-)

Are you planning to integrate _backward_, _stepwise_ and other approaches of selection?

**Comment by HannaMeyer** [comment]
Backward selection is implemented in the caret package (https://topepo.github.io/caret/recursive-feature-elimination.html). But it cannot be used to avoid overfitting caused by to spatial dependencies in the data because it is based on the internal variable importance ranking (see https://www.sciencedirect.com/science/article/pii/S1364815217310976).

I fully understand your preference of a selection based on theoretical considerations. But an automatic selection does not mean there shouldn't be theoretical considerations in advance. But testing how certain variables behave in the statistical model is important to avoid overfitting and that can be challenging to see without an automatic strategy.

**Comment by tobwen** [comment]
Thanks for your reply.

Yet, I don't have access to the paper via our university library. However, I have already asked to buy the article. I will test your approach intensively next week with my own data - I am very excited about the results.
